services:

  spring-ai-db:
    build:
      dockerfile: ./Dockerfile
      context: postgres
    restart: always
    container_name: spring-ai-db
    ports:
      - "25432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pgadmin
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

volumes:
  postgres_data:
